### ISSUE TITLE
BaseStation: Planned Changes Consolidation

### ISSUE THREAD

**Issue by Broken-Admin** [SHC-ASTRA/rover-Basestation-Release#17]
### General UI
- [ ] Widget grid display
    - A grid displaying the space that a widget may take up on the front end
- [x] Larger initial widget space
    - Make the initial widget space larger
- [ ] Sidebar revisions
    - [x] Decrease size of sidebar
    - [x] Improve sidebar colors and display
    - [ ] Search Bar
    - [ ] Clean up widgets on sidebar
- [ ] Stylize widgets
- [ ] Trash area where widgets can be dropped and removed
    - Removal needs to happen in edit mode, not live mode
    - Currently the delete button cannot be clicked due to button behavior in edit more
- [x] Deny widget drops during live mode
    - Modify widget drop logic
### Development Complexity
- [ ] Clean up feedback topics
    - Make use of interface files
    - Integration into a better database 
- [ ] Block two clients from using the same control widget at the same time
    - Integrate with backend and API
- [ ] Blocking widgets based on currently active widgets
     - Core control should not be up with autonomy 
- [ ] Battery voltage bar on taskbar
- [ ] Handle different controller implementations (detect and bind type)
    - QoL, I am not a fan of this idea but it is possible
- [ ] settings/diagnostics page
- [ ] host a network from base station and have a mobile version?? teehee
### Map-Specific
- [ ] Change map library
- [ ] Map implementation on computers where the server is not running
    - Weird graphical errors happen when running 
- [ ] Orientation widget
    - Can be displayed on map widget
- [ ] Add more detailed map
    - Topography as an alternative
### ROS

- [ ] Submodules for msg files
- [ ] Splitting into multiple nodes
    - Arm, Autonomy, Biosensor, Core, Camera, Drone
- [ ] Node Composition or Launch Files
- [ ] Mirror API endpoints with new ROS nodes
    - Further discussion necessary
### API
 - [ ] using error codes on API properly
- [ ] Namespace API to `/api/[route]`
### General
- [x] #29
- [ ] #30
    - Inside virtual environment causes errors 
    - Possibly move away from `venv`
- [ ] Changing core controller to match arm controller implementation
    - Interface file integration for core control
- [ ] Backend database
    - Python has an [official sqlite3 library](https://docs.python.org/3/library/sqlite3.html)

## Physical / Electrical
- [ ] Cover panel redesign
    - Add drop-down for keyboards
    - Redesign into smaller parts to remove flexing
- [ ] Removal of foam
    - Unnecessary and introduces more issues
- [ ] USB hubs replacement
    - Introducing power draw issues
- [ ] Further investigate issues with radios causing power issues
- [ ] Introduce another powerstrip
    - Better cable management, cable ties are a must

**Comment by ryleu** [comment]
these need to be split between https://github.com/SHC-ASTRA/rover-Basestation-Backend and https://github.com/SHC-ASTRA/rover-Basestation-Frontend properly

**Comment by ryleu** [comment]
we are starting from scratch :)
