### ISSUE TITLE
BaseStation: Break Into Github Submodules

### ISSUE THREAD

**Issue by Broken-Admin** [SHC-ASTRA/rover-Basestation-Release#18]
Because of BaseStation's implementation as a backend server with a frontend React page, it would make much sense to break it into multiple GitHub repositories so that concurrent changes can happen much easier.

The process would ideally go as below, after post-2024 changes (#15 & #16) are completed. The following (#17) refactor and redesign could easily proceed without blockers due to a large merge needing to happen each time work is done concurrently.

1. Current BaseStation repository is archived as-is
2. Archived repository is forked twice
3. Forked repositories delete the unnecessary server or front-end directory and are reorganized to provide their respective module on the top-level repository

**Comment by Broken-Admin** [comment]
See #19

**Comment by TristanMcGinnis** [comment]
Note for clarity:
Targeting 3 repos

- rover-Basestation-Backend
- rover-Basestation-Frontend
- rover-Basestation-Release (naming TBD here)

"Release" repo for Basestation will have backend and frontend as separate submodules.

**Comment by Broken-Admin** [comment]
Resolved by merge of #21
