### ISSUE TITLE
Resolve "fork" association to submodule repositories

### ISSUE THREAD

**Issue by Broken-Admin** [SHC-ASTRA/rover-Basestation-Release#23]
Remove the association of rover-Basestation-Frontend and rover-Basestation-Backend to be forks of rover-Basestation-Release

**Comment by Broken-Admin** [comment]
[Relevant Documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork)

**Comment by ryleu** [comment]
making `-Release` private and then public again should work

**Comment by ryleu** [comment]
fixed!
